// <auto-generated />
namespace Web_API_tutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingRentals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingRentals));
        
        string IMigrationMetadata.Id
        {
            get { return "202001271652461_AddingRentals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
